### ISSUE TITLE
"undefined" is not valid JSON

### ISSUE THREAD

**Issue by jekakiev** [technovangelist/airenamer#5]
![418786724_299577919779736_8050834589032158300_n](https://github.com/technovangelist/airenamer/assets/60492248/5fe1fd35-7b00-4627-b756-a029554590f0)

error: Uncaught (in promise) SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at getkeywords (file:///home/runner/work/airenamer/airenamer/main.ts:20:25)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async file:///home/runner/work/airenamer/airenamer/main.ts:33:24

**Comment by technovangelist** [comment]
that should be fixed now. thanks
